[package]
name = "rocker"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo = "0.80.0"
ratatui = "0.27.0"
semver = { version = "1.0.23", features = ["serde"] }
serde = { version = "1.0.204", features = ["rc"] }
serde_json = "1.0.120"
toml = "0.8.14"
url = { version = "2.5.2", features = ["serde"] }
