name: Test

on:
  - push
  - pull_request

jobs:

  test:
    name: Cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo install pueue sqlx-cli
      - run: pueued -d
      - run: cargo sqlx db create
      - run: cargo sqlx migrate run --source ${PWD}/crates/jocker-lib/migrations
      - run: cargo test --all-features
